# Generated by Django 5.0.6 on 2024-05-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emppasswd',
            field=models.CharField(max_length=256),
        ),
    ]
