# Generated by Django 5.0.6 on 2024-06-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai', '0002_alter_employee_emppasswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.CharField(max_length=8)),
                ('patfname', models.CharField(max_length=64)),
                ('patlname', models.CharField(max_length=64)),
                ('medicineid', models.CharField(max_length=8)),
                ('medicinename', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=8)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
